#
# Build stage
#
FROM maven:3.6.0-jdk-11-slim AS build
COPY src /home/app/src
COPY pom.xml /home/app
RUN mvn -f /home/app/pom.xml clean package --quiet -DskipTests=True

#
# Package stage
#
FROM openjdk:11-jre-slim
ARG BUILD_ENV
COPY --from=build /home/app/target/app.jar /usr/local/lib/app.jar
RUN mkdir -p logs
EXPOSE 8080
ENTRYPOINT [ "java",  "-jar", "/usr/local/lib/app.jar"]