version: '3.9'
x-logging:
  &default-logging
  options:
    max-size: '10m'
    max-file: '1'
  driver: json-file

services:
  zookeeper:
    container_name: zookeeper
    image: bitnami/zookeeper:3.8
    restart: unless-stopped
    environment:
      ALLOW_ANONYMOUS_LOGIN: 'yes'
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper-data:/bitnami"
  kafka:
    container_name: kafka
    image: bitnami/kafka:3.2.1
    restart: unless-stopped
    environment:
      KAFKA_BROKER_ID: 1
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,CLIENT:SASL_PLAINTEXT
      KAFKA_CFG_LISTENERS: INTERNAL://:9091,CLIENT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://kafka:9091,CLIENT://kafka:9092
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CLIENT_USERS: ${KAFKA_USERNAME:-user}
      KAFKA_CLIENT_PASSWORDS: ${KAFKA_PASSWORD_ENCRYPTED:-bitnami}
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_ENABLE.AUTO.COMMIT: 'false'
      KAFKA_CFG_ENABLE.IDEMPOTENCE: 'true'
      KAFKA_CFG_REQUIRED_ACKS: all
      KAFKA_CFG_ISOLATION_LEVEL: read_committed
      KAFKA_CFG_HEARTBEAT_INTERVAL_MS: 3000
      KAFKA_CFG_SESSION_TIMEOUT_MS: 10000
      KAFKA_CFG_AUTO_OFFSET_RESET: earliest
      KAFKA_CFG_MAX_PARTITION_FETCH_BYTES: 1048576
    ports:
      - "9091:9091"
      - "9092:9092"
    volumes:
      - "kafka-data:/bitnami/kafka"                     
    depends_on:
      - zookeeper
  kafdrop:
    container_name: kafdrop
    image: obsidiandynamics/kafdrop:latest
    restart: unless-stopped
    ports:
      - 9000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:9091
    depends_on:
      - kafka

networks:
  default:
    name: ${SANDBOX_PROJECT}
volumes:
  zookeeper-data: {}
  kafka-data: {}